/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcceptServiceModal: typeof import('./components/modals/AcceptServiceModal.vue')['default']
    AppAcceptServiceButton: typeof import('./../../../../../../src/views/ServicesQueue/AcceptServiceButton.vue')['default']
    AppExtra: typeof import('./../../../../../../src/components/ExtraIcon.vue')['default']
    AppLoading: typeof import('./../../../../../../src/components/Loading.vue')['default']
    AppLogin: typeof import('./../../../../../../src/components/Login.vue')['default']
    AppMenuDrawer: typeof import('./components/AppMenuDrawer.vue')['default']
    AppMenuTrigger: typeof import('./components/AppMenuTrigger.vue')['default']
    AppMiniLoading: typeof import('./../../../../../../src/components/MiniLoading.vue')['default']
    AppModals: typeof import('./../../../../../../src/components/Modals.vue')['default']
    AppServiceRealtimeHelper: typeof import('./../../../../../../src/components/ServicesRealtimeHelper/ServiceRealtimeHelper.vue')['default']
    AppServicesRealtimeHelper: typeof import('./../../../../../../src/components/ServicesRealtimeHelper/ServicesRealtimeHelper.vue')['default']
    AppSubpanel: typeof import('./../../../../../../src/Subpanel.vue')['default']
    AppUpdates: typeof import('./../../../../../../src/components/Updates.vue')['default']
    ExtraAgentsModal: typeof import('./components/modals/ExtraAgentsModal.vue')['default']
    ExtraChampionsModal: typeof import('./components/modals/ExtraChampionsModal.vue')['default']
    ExtraIcon: typeof import('./components/ExtraIcon.vue')['default']
    GameButton: typeof import('./components/GameButton.vue')['default']
    GameIcon: typeof import('./components/GameIcon.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    LogoutConfirmModal: typeof import('./components/modals/LogoutConfirmModal.vue')['default']
    MiniLoading: typeof import('./components/MiniLoading.vue')['default']
    Modals: typeof import('./components/Modals.vue')['default']
    MyServicesDropdown: typeof import('./components/MyServicesDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceRealtimeHelper: typeof import('./components/ServicesRealtimeHelper/ServiceRealtimeHelper.vue')['default']
    ServicesQueueDropdown: typeof import('./components/ServicesQueueDropdown.vue')['default']
    ServicesRealtimeHelper: typeof import('./components/ServicesRealtimeHelper/ServicesRealtimeHelper.vue')['default']
    Updates: typeof import('./components/Updates.vue')['default']
  }
}
